Repository onflow/flow, pull requests merged in 2020-11, with the labels that each got.

#61 Update earn.mdx
  docs/content/token/earn.mdx
Labels: Documentation

#147 adds high level intro to staking
  docs/content/token/staking/index.mdx
  docs/content/token/staking/technical.mdx
  docs/gatsby-config.js
Labels: Documentation, T-Documentation 📃

#151 Remove "docset" dropdown menu from all pages
  docs/content/assets/apple-logo.svg
  docs/content/assets/badminton-player.svg
  docs/content/assets/diving.svg
  docs/content/assets/head-light.svg
  docs/content/assets/paragliding.svg
  docs/content/assets/react-logo.svg
  docs/content/assets/weightlift.svg
  docs/content/components/docset-sidebar.js
  docs/content/components/workout-menu-item.js
  docs/content/index.mdx
  docs/gatsby-config.js
  docs/plugins/gatsby-theme-flow/gatsby-node.js
  docs/plugins/gatsby-theme-flow/index.js
  docs/plugins/gatsby-theme-flow/src/components/docset-switcher.js
  docs/plugins/gatsby-theme-flow/src/components/page-layout.js
  docs/plugins/gatsby-theme-flow/src/components/sidebar-nav.js
  docs/plugins/gatsby-theme-flow/src/utils/typography.js
Labels: Documentation

#153 Revamp staking docs for new content structure
  docs/content/staking/locked-delegation-guide.mdx
  docs/content/staking/locked-staking-guide.mdx
  docs/content/staking/locked-third-party-operator.mdx
  docs/content/staking/staking-transactions.mdx
  docs/content/staking/technical-overview.mdx
  docs/gatsby-config.js
Labels: Documentation

#150 Re-structure staking, delegation and node operation documentation
  docs/content/staking/events.mdx
  docs/content/staking/flow-stake-delegation.png
  docs/content/staking/flow-staking-new-operators.png
  docs/content/staking/index.mdx
  docs/content/staking/locked-delegation-guide.mdx
  docs/content/staking/locked-staking-guide.mdx
  docs/content/staking/locked-third-party-operator.mdx
  docs/content/staking/rewards.mdx
  docs/content/staking/stake-slashing.mdx
  docs/content/staking/technical-overview.mdx
  docs/content/staking/transactions-locked.mdx
  docs/content/staking/transactions.mdx
  docs/content/token/locked-account-setup.mdx
  docs/content/token/staking/locked/index.mdx
  docs/content/token/staking/locked/node-operators.mdx
  docs/content/token/staking/locked/power-users.mdx
  docs/content/token/staking/locked/stakers.mdx
  docs/gatsby-config.js
Labels: Documentation

#149 Feature: Updated Staking Documentation
  docs/content/components/tutorial-image.js
  docs/content/concepts/flow-concepts/token-staking.mdx
  docs/content/node-operation/faq.mdx
  docs/content/node-operation/index.mdx
  docs/content/node-operation/monitoring-nodes.mdx
  docs/content/node-operation/node-bootstrap.mdx
  docs/content/node-operation/node-roles.mdx
  docs/content/node-operation/node-setup.mdx
  docs/content/node-operation/spork.mdx
  docs/content/protocol/core-contracts/flow-fees.mdx
  docs/content/protocol/core-contracts/flow-id-table-staking.mdx
  docs/content/protocol/core-contracts/flow-token.mdx
  docs/content/protocol/core-contracts/fungible-token.mdx
  docs/content/protocol/core-contracts/index.md
  docs/content/protocol/core-contracts/locked-tokens.mdx
  docs/content/staking/events.mdx
  docs/content/staking/index.mdx
  docs/content/staking/locked-delegation-guide.mdx
  docs/content/staking/locked-staking-guide.mdx
  docs/content/staking/locked-third-party-operator.mdx
  docs/content/staking/rewards.mdx
  docs/content/staking/stake-slashing.mdx
  docs/content/staking/technical-overview.mdx
  docs/content/token/locked-account-setup.mdx
  docs/content/token/staking/flow-stake-delegation.png
  docs/content/token/staking/flow-staking-new-operators.png
  docs/content/token/staking/locked/delegators.mdx
  docs/content/token/staking/locked/index.mdx
  docs/content/token/staking/locked/node-operators.mdx
  docs/content/token/staking/locked/power-users.mdx
  docs/content/token/staking/locked/stakers.mdx
  docs/content/token/staking/rewards.mdx
  docs/content/token/staking/stake-slashing.mdx
  docs/gatsby-config.js
  docs/plugins/gatsby-theme-flow/src/components/header-nav.js
  docs/plugins/gatsby-theme-flow/src/components/page-layout.js
  docs/plugins/gatsby-theme-flow/src/components/sidebar-nav.js
Labels: Documentation

#169 adding more operator FAQs; corrections to node monitoring page
  docs/content/node-operation/faq.mdx
  docs/content/node-operation/flow-architecture.png
  docs/content/node-operation/monitoring-nodes.mdx
  docs/content/node-operation/node-bootstrap.mdx
  docs/content/node-operation/node-setup.mdx
Labels: Document

#174 Update mainnet.mdx
  docs/content/concepts/flow-concepts/mainnet.mdx
Labels: Improvement

#199 Prepare staking and node-operation docs for live
  docs/content/concepts/flow-concepts/accessing-testnet.mdx
  docs/content/node-operation/spork.mdx
  docs/content/staking/technical-overview.mdx
  docs/content/token/index.mdx
  docs/gatsby-config.js
  docs/vercel.json
Labels: Docs Site

#202 Add Testnet draft docs to site and sidebar.
  docs/content/concepts/flow-concepts/devnet.mdx
  docs/content/concepts/flow-concepts/testnet.mdx
  docs/content/emulator/index.md
  docs/content/guides/dapp-deployment/testnet-deployment.md
  docs/content/guides/dapp-deployment/testnet-testing.md
  docs/content/sdks/golang/index.md
  docs/content/token/locked-account-setup.mdx
  docs/gatsby-config.js
Labels: Docs Site

#203 Add Cadence best practice docs.
  docs/content/guides/cadence/design-patterns.mdx
  docs/content/guides/cadence/dragons.mdx
  docs/gatsby-config.js
Labels: Docs Site, Document

#208 adds lease section
  docs/content/token/delivery.mdx
Labels: Docs Site

#211 Add missing staking pages.
  docs/gatsby-config.js
Labels: Docs Site

#209 Content & style updates to "Testnet Deployment Guidelines"
  docs/content/guides/dapp-deployment/testnet-deployment.md
Labels: Docs Site, Document

#216 Add missing sidebar pages.
  docs/gatsby-config.js
Labels: Docs Site
