Repository onflow/flow, pull requests merged in 2020-10, with the labels that each got.

#67 Added contracts on the access API Account entity to support multiple contracts per account
  docs/content/protocol/access-api.md
  protobuf/flow/entities/account.proto
  protobuf/go/flow/entities/account.pb.go
  protobuf/go/flow/legacy/entities/account.pb.go
Labels: Access API, documentation

#70 Replace origin on search results
  docs/plugins/gatsby-theme-flow/src/components/search.js
Labels: Feedback, bug

#136 Add addresses for other contracts to the docs
  docs/content/token/staking/locked/transactions.mdx
Labels: documentation

#141 Update documentation for locked tokens transaction templates
  docs/content/token/staking/locked/delegators.mdx
  docs/content/token/staking/locked/stakers.mdx
  docs/content/token/staking/locked/transactions.mdx
Labels: Documentation
