Repository onflow/flow, pull requests merged in 2022-02, with the labels that each got.

#787 add reference for service account addresses
  docs/content/core-contracts/service-account.mdx
  docs/gatsby-config.js
Labels: Docs Site, T-Documentation 📃

#801 Add documentation for HTTP API
  docs/content/http-api.mdx
  docs/content/index.mdx
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
  docs/plugins/gatsby-theme-flow/gatsby-node.js
  docs/plugins/gatsby-theme-flow/src/components/content-wrapper.js
  docs/plugins/gatsby-theme-flow/src/components/header.js
  docs/plugins/gatsby-theme-flow/src/components/http-api.js
  docs/plugins/gatsby-theme-flow/src/components/page-content.js
  docs/plugins/gatsby-theme-flow/src/components/page-layout.js
  docs/plugins/gatsby-theme-flow/src/components/sidebar-nav.js
  docs/plugins/gatsby-theme-flow/src/components/sidebar.js
  docs/plugins/gatsby-theme-flow/src/components/templates/base.js
  docs/plugins/gatsby-theme-flow/src/components/templates/changelog.js
  docs/plugins/gatsby-theme-flow/src/styles.less
Labels: Improvement

#849 [HTTP API] Update descriptions
  openapi/access.yaml
Labels: Docs Site
